KillTimer(lourider);
         KillTimer(stretrace);
         KillTimer(Time);


          KillTimer(musicremove11);
                 KillTimer(musicremove);
                 KillTimer(musicremove1);
                 KillTimer(musicremove2);
                 KillTimer(musicremove3);
                 KillTimer(musicremove4);
                 KillTimer(musicremove5);
                 KillTimer(musicremove6);
                 KillTimer(musicremove7);
                 KillTimer(musicremove8);
                 KillTimer(musicremove9);
                 KillTimer(musicremove10);
                 KillTimer(musicremove11);
                 KillTimer(musicremove11);
                 KillTimer(musicremove10);
                 KillTimer(musicremove10);
                 KillTimer(lourider);
                 KillTimer(stretrace);
